#!/usr/bin/perl
$|++;

use strict;
use lib "./";
use CGI;
use DBI;
use CVR;
#use Config::IniFiles ();
use POSIX qw(strftime);
use Data::Dumper;
#use CGI::App::Config;
use JSON;

my %EVENTS;
my $dbh;

$EVENTS{"getSongs"} = \&db_get_songs;
$EVENTS{"getAlbums"} = \&db_get_albums;
$EVENTS{"getArtists"} = \&db_get_artists;

# Signal handling
$SIG{TERM} = $SIG{QUIT} = $SIG{INT}  = \&STOP;
$SIG{CHLD} = \&handle_signal_child;
$SIG{__DIE__} = sub {
	STOP();
};

print STDERR $$.":Iniciando Dbhandle";
if(START() != 0) {
	print STDERR "Fallo al iniciar";
	exit 1;
}

while(<STDIN>) {
	my $event;
	$event = parse_msg($_);
	my $response;
	$response->{'error'} = 0;
	$response->{'error_text'} = "";
	$response->{'reponse'} = "";
	$response->{'id'} = "";

	if(!$event) {
		$response->{'error'} = -2;
		$response->{'error_text'} = "Fallo la peticion";
		print STDERR "ERROR de mensaje\n";
	} else {
		$response->{'id'} = $event->{'id'};
		if($EVENTS{$event->{"event"}}) {
			my $ret = $EVENTS{$event->{"event"}}($event->{"params"});
			if($ret == -1) {
				$response->{'error'} = -1;
				$response->{'error_text'} = "Fallo la peticion";
				print STDERR "Evento $event->{event} fallo\n";
			} else {
				$response->{'reponse'} = $ret;
			}
		} else {
			$response->{'error_text'} = "Evento $event->{event} inexistente\n";
			$response->{'error'} = -3;
		}
	}
	
	print STDOUT encode_json($response);
	print STDOUT "\n";
	



	sleep(1);
} 

STOP();

sub START 
{
	$dbh = DBI->connect('dbi:mysql:oruga:localhost', 'root', 'oruga') || die $DBI::errstr;

	return 0;        
}

sub STOP 
{
	my $signal = shift;
	$dbh->disconnect;

	exit(0);
}

sub parse_msg
{
	my $msg = shift;

	if(!$msg) {
		return undef;
	}
	my $ret = $msg =~ /^(\d+):([a-zA-Z_-]+):(\S+)$/;
	if(!$ret) {
		return undef;
	}

	my $data;
	$data->{'id'} = $1;
	$data->{'event'} = $2;
	
	my $q = new CGI($3);
	if(!$q) {
		return undef;
	}
	$data->{'params'} = $q;

	return $data;
}


sub db_get_songs
{
	my $params = shift;

	my $obj = new Objdb::CVR::Songs();
	$obj->db($dbh);
	$obj->enableTables(["album"]);
	$obj->join("album")->enableTables(["artist"]);

	my $where = "1";
	$where .= " AND songs.id = ".$params->{'param'}->{'idSong'}->[0] if($params->{'param'}->{'idSong'});
	$where .= " AND songs.idalbum = ".$params->{'param'}->{'idAlbum'}->[0] if($params->{'param'}->{'idAlbum'});
	$where .= " AND songs.name like '%".$params->{'param'}->{'wordSong'}->[0]."%'" if($params->{'param'}->{'wordSong'});
	$where .= " AND songsalbum.idartist = ".$params->{'param'}->{'idArtist'}->[0] if($params->{'param'}->{'idArtist'});
	$where .= " AND songsalbum.name like '%".$params->{'param'}->{'wordAlbum'}->[0]."%'" if($params->{'param'}->{'wordAlbum'});
	$where .= " AND songsalbumartist.name like '%".$params->{'param'}->{'wordArtist'}->[0]."%'" if($params->{'param'}->{'wordArtist'});
	
	$obj->where($where);
	$obj->limit_from(($params->{'param'}->{'limitFrom'}->[0]  > 0) ? $params->{'param'}->{'limitFrom'}->[0] : 0);
	$obj->limit_count(($params->{'param'}->{'limitCount'}->[0] > 0) ? $params->{'param'}->{'limitCount'}->[0] : 10);
	$obj->order_by(($params->{'param'}->{'orderBy'}->[0] > 0) ? $params->{'param'}->{'orderBy'}->[0] : "songs.name ASC");

	my $result = $obj->fetchall();
	if($obj->error) {
		print STDERR "query error: $obj->{_log}\n";
		return -1;
	}

	return $result;
}


sub db_get_albums
{
	my $params = shift;

	my $obj = new Objdb::CVR::Albums();
	$obj->db($dbh);
	$obj->enableTables(["artist"]);

	my $where = "1";
	$where .= " AND albums.id = ".$params->{'param'}->{'idAlbum'}->[0] if($params->{'param'}->{'idAlbum'});
	$where .= " AND albums.idartist = ".$params->{'param'}->{'idArtist'}->[0] if($params->{'param'}->{'idArtist'});
	$where .= " AND albums.name like '%".$params->{'param'}->{'wordAlbum'}->[0]."%'" if($params->{'param'}->{'wordAlbum'});
	$where .= " AND albumsartist.name like '%".$params->{'param'}->{'wordArtist'}->[0]."%'" if($params->{'param'}->{'wordArtist'});
	
	$obj->where($where);
	$obj->limit_from(($params->{'param'}->{'limitFrom'}->[0]  > 0) ? $params->{'param'}->{'limitFrom'}->[0] : 0);
	$obj->limit_count(($params->{'param'}->{'limitCount'}->[0] > 0) ? $params->{'param'}->{'limitCount'}->[0] : 10);
	$obj->order_by(($params->{'param'}->{'orderBy'}->[0] > 0) ? $params->{'param'}->{'orderBy'}->[0] : "albums.name ASC");

	my $result = $obj->fetchall();
	if($obj->error) {
		print STDERR "query error: $obj->{_log}\n";
		return -1;
	}

	return $result;
}

sub db_get_artists
{
	my $params = shift;

	my $obj = new Objdb::CVR::Artists();
	$obj->db($dbh);

	my $where = "1";
	$where .= " AND artists.id = ".$params->{'param'}->{'idArtist'}->[0] if($params->{'param'}->{'idArtist'});
	$where .= " AND artists.name like '%".$params->{'param'}->{'wordArtist'}->[0]."%'" if($params->{'param'}->{'wordArtist'});
	
	$obj->where($where);
	$obj->limit_from(($params->{'param'}->{'limitFrom'}->[0]  > 0) ? $params->{'param'}->{'limitFrom'}->[0] : 0);
	$obj->limit_count(($params->{'param'}->{'limitCount'}->[0] > 0) ? $params->{'param'}->{'limitCount'}->[0] : 10);
	$obj->order_by(($params->{'param'}->{'orderBy'}->[0] > 0) ? $params->{'param'}->{'orderBy'}->[0] : "artists.name ASC");

	my $result = $obj->fetchall();
	if($obj->error) {
		print STDERR "query error: $obj->{_log}\n";
		return -1;
	}

	return $result;
}
